 <?php // List mode ?>
    <?php if($layout_mode !='grid'): ?>
		 <div class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?> product-block" itemtype="http://schema.org/Product" itemscope>
			<div class="row ">
				<?php // Product Image ?>
				<?php $productId = $_product->getId(); ?>
				<div class="col-lg-4 col-sm-4 col-xs-12">
					<?php
						$swap_class = "";
						if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number , $list_image_width, $list_image_height)) {
								$swap_class = "swap";
						 } 
					?>

					<div class="image <?php echo $swap_class; ?>">
						<?php 
							if($enable_sale_icon) {
								$_product2 = Mage::getModel('catalog/product')->load($productId);
								// Get the Special Price
								$specialprice = $_product2->getSpecialPrice(); 
								// Get the Special Price FROM date
								$specialPriceFromDate = $_product2->getSpecialFromDate();
								// Get the Special Price TO date
								$specialPriceToDate = $_product2->getSpecialToDate();
								// Get Current date
								$today =  time();
							 
								if ($specialprice) {
									if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
							?>
								<span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
							<?php  
									}
								}
							}
							?>
						 <?php

							if($enable_new_icon) {
								$is_new = Mage::helper("ves_tempcp")->checkProductIsNew( $_product );

								if($is_new) { ?>
								<span class="new-icon"><span><?php echo $this->__("New");?></span></span>
								<?php

								}
							}
						?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						 <?php if($swap_class) { ?>
							<span class="hover-image">
								<a class="img" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
							</span>
							<?php } ?>
							
						
						<div class="product-colorbox">
							<?php if ($quickview) { ?>
								<a class="ves-colorbox ves-quickview" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getProductUrl() ); ?>"><i class="fa fa-eye"></i></a>
							<?php } ?>
							<?php if( $enable_pzoom ) { ?>								
							<?php
								if(!isset($_product2)) {
									$_product2 = Mage::getModel('catalog/product')->load($productId);
								}
								
							?>

							<a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom ves-zoom" rel="colorbox" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><i class="fa fa-search-plus"></i></a>
						<?php } ?>
						</div>
					</div>
					
				</div>
				<?php // Product description ?>
				<div class="col-lg-8 col-sm-8 col-xs-12">
					<div class="product-meta product-shop">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						<?php if($_product->getRatingSummary()): ?>
						<div class="rating">
							<?php echo $this->getReviewsSummaryHtml($_product) ?>
						</div>
						<?php endif; ?>
						<div class="price">
							<?php echo $this->getPriceHtml($_product, true) ?>
						</div>
						<?php if($_product->isSaleable()): ?>
						
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						<div class="desc std">
							<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<div class="actions">
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
							<?php if($show_compare_wishlist): ?>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<li class="wishlist">
										<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i></a></li>
									</li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li class="compare">
									<a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-copy"></i></a>
								</li>
								<?php endif; ?>
							</ul>
							<?php endif; ?>
						</div>

					</div>
				</div>
			</div>
	</div>
    <?php else: ?>

    <?php // Grid Mode ?>
    <?php $productId = $_product->getId(); ?>
		<div class="col-xs-12 col-lg-<?php echo $span;?> col-sm-<?php echo $small;?> col-<?php echo $mini;?> _item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> product-col <?php if($layout_mode !='grid'){ echo "col-fullwidth";} ?> ">
			<div class="product-block" itemscope  itemtype="http://schema.org/Product">
				<?php
						$swap_class = "";
						if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) {
								$swap_class = "swap";
						 } 
					?>
				<div class="image <?php echo $swap_class; ?>">
					<?php 
						if($enable_sale_icon) {
							$_product2 = Mage::getModel('catalog/product')->load($productId);
							// Get the Special Price
							$specialprice = $_product2->getSpecialPrice(); 
							// Get the Special Price FROM date
							$specialPriceFromDate = $_product2->getSpecialFromDate();
							// Get the Special Price TO date
							$specialPriceToDate = $_product2->getSpecialToDate();
							// Get Current date
							$today =  time();
						 
							if ($specialprice) {
								if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
						?>
								<span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
						<?php  
								}
							}
						}
						?>
						 <?php
						 if($enable_new_icon) {
							$is_new = Mage::helper("ves_tempcp")->checkProductIsNew( $_product );
							
							if($is_new) { ?>
							<span class="new-icon"><span><?php echo $this->__("New");?></span></span>
							<?php

							}
						}
						?>
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					<?php if($swap_class) { ?>
							<span class="hover-image">
								<a class="img" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
							</span>
					<?php } ?>
				   
					
					<div class="product-colorbox">
						<?php if ($quickview) { ?>
							<a class="ves-colorbox ves-quickview" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getProductUrl() ); ?>"><i class="fa fa-eye"></i></a>
						<?php } ?>
						<?php if( $enable_pzoom ) { ?>								
						<?php
							if(!isset($_product2)) {
								$_product2 = Mage::getModel('catalog/product')->load($productId);
							}
						?>

						<a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom ves-zoom" rel="colorbox" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><i class="fa fa-search-plus"></i></a>
					<?php } ?>
					</div>

				</div>
				<div class="product-info">
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				<?php if($enable_short_desc) { ?>
						<div class="desc std">
							<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
				<?php } ?>
					<?php if($_product->getRatingSummary()): ?>
					<div class="rating">
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					</div>
					<?php endif; ?>
					<div class="price">
						<?php echo $this->getPriceHtml($_product, true) ?>
					</div>
					<div class="actions">
						<?php if($_product->isSaleable()): ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						<?php if($show_compare_wishlist): ?>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-copy"></i></a></li>
							<?php endif; ?>
						</ul>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
    <?php endif; ?>