<?php 
$moduleId = rand().time();
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<div class="<?php echo $prefix; ?> box search_box">
	<form method="GET" action="<?php echo $this->getCatalogSearchLink(); ?>" id="search_form_<?php echo $moduleId;?>">
		<?php if(!empty($categories)) { ?>
			<div class="filter_type category_filter pull-left">
				<span class="fa fa-caret-down"></span>
				<select name="category_id">
					<option value="0"><?php echo $this->__("All Categories"); ?></option>
					<?php echo $categories; ?>
				</select>
			</div>
		<?php } ?>
		<div id="search<?php echo $moduleId ?>" class="search pull-left">
			<input type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" autocomplete="off" placeholder="<?php echo $this->__('Search entire store here...');?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-search ">
			<span class="button-search fa fa-search"></span>
		</div>
	</form>
	<div class="clear clr"></div>
</div>

<script type="text/javascript">
(function($) {
	$("#search<?php echo $moduleId ?> span:first").mouseover(function(){
		var $this = $(this);
		var $input = $(".category_filter select[name=\"category_id\"]"); 
		if ($input.is("select") && !$('.lfClon').length) {
			var $clon = $input.clone();
			var getRules = function($ele){ return {
				position: 'absolute',
				left: $ele.offset().left,
				top: $ele.offset().top,
				width: $ele.outerWidth(),
				height: $ele.outerHeight(),
				background: '#f9f9f9',
				fontSize: '13px',
				color: '#8c8c8c',
				opacity: 0,
				margin: 0,
				padding: 0
			};};
			var rules = getRules($input);
			$clon.css(rules);
			$clon.on("mousedown.lf", function(){
				$clon.css({
					marginLeft: $input.offset().left - rules.left,
					marginTop: $input.offset().top - rules.top,
				});
				$clon.on('change blur', function(){
					$input.val($clon.val()).show();
					$clon.remove();
				});
				$clon.off('.lf');
			});
			$clon.on("mouseout.lf", function(){
				$(this).remove();
			});
			$clon.prop({id:'',className:'lfClon'});
			$clon.appendTo('body');
		}
	});

	var selector = '#search<?php echo $moduleId ?>';
	var text_price = "<?php echo $this->__('Price');?>";
	var total = 0;
	var show_image = true;
	var show_price = true;
	var search_sub_category = true;
	var search_description = true;

	$(selector).find('.button-search').bind('click', function(){
		url = "<?php echo $this->getCatalogSearchLink(); ?>";
			 
		var category_id = $(".category_filter select[name=\"category_id\"]").first().val();
		if(typeof(category_id) == 'undefined')
			category_id = 0;

		var search = $('input[name=\'<?php echo $catalogSearchHelper->getQueryParamName() ?>\']').attr('value');
		
		if(category_id) {
			url += '?cat=' + encodeURIComponent(category_id);
			if (search) {
				url += '&q=' + encodeURIComponent(search);
			}
		} else if(search) {
			url += '?q=' + encodeURIComponent(search);
		}
		
		location = url;
	});

	$(selector).find('input[name=\'<?php echo $catalogSearchHelper->getQueryParamName() ?>\']').bind('keydown', function(e) {
		if (e.keyCode == 13) {
			url = "<?php echo $this->getCatalogSearchLink(); ?>";
			
			var category_id = $(".category_filter select[name=\"category_id\"]").first().val();
			if(typeof(category_id) == 'undefined')
				category_id = 0;

			var search = $('input[name=\'<?php echo $catalogSearchHelper->getQueryParamName() ?>\']').attr('value');
			
			if(category_id) {
				url += '?cat=' + encodeURIComponent(category_id);
				if (search) {
					url += '&q=' + encodeURIComponent(search);
				}
			} else if(search) {
				url += '?q=' + encodeURIComponent(search);
			}
			location = url;
		}
	});
	
	$(document).ready( function(){
		$(selector).find('input[name=\'<?php echo $catalogSearchHelper->getQueryParamName() ?>\']').autocomplete({
			delay: 500,
			position: {
	                my: "left top",
	                at: "left bottom",
	                collision: "none"
	        },
			open: function() {
				
	            //autocomplete.css("top", newTop);

		    },
			source: function(request, response) {
				var category_id = $(".category_filter select[name=\"category_id\"]").first().val();
				if(typeof(category_id) == 'undefined')
					category_id = 0;
				var limit = 5;
				var text = encodeURIComponent(request.term);

				var search_sub_category = search_sub_category?'&sub_category=true':'';
				var search_description = search_description?'&description=true':'';
				var formkey =  $("input[name='form_key']").val();
				if(text.length > 1){
				$.ajax({
					url: '<?php echo $listProductLink ?>',
					dataType: 'json',
					data: 'filter_category_id='+category_id+'&limit='+limit+search_sub_category+search_description+'&filter_name='+encodeURIComponent(request.term),
					type:'POST',
					success: function(json) {
						response($.map(json, function(item) {
							if($('.vesautosearch_result')){
								$('.vesautosearch_result').first().html("");
							}
							total = 0;
							if(item.total){
								total = item.total;
							}
							return {
								price: item.price,
								html: item.html,
								label: item.name,
								image: item.image,
								link:  item.link,
								value: item.product_id
							}
						}));
					}
				});
				}
			},
			select: function(event, ui) {
				return false;
			},
			focus: function(event, ui) {
				return false;
			}
		})
			$(selector).find('input[name=\'<?php echo $catalogSearchHelper->getQueryParamName() ?>\']').data( "autocomplete" )._renderMenu = function(ul,b){
				var g=this;
				$.each(b,function(c,f){g._renderItem(ul,f)});
				var category_id = $(".category_filter select[name=\"category_id\"]").first().val();
				if(typeof(category_id) == 'undefined')
					category_id = 0;

				category_id = parseInt(category_id);
				var text_view_all = '<?php echo $this->__("View all %s items");?>';
				text_view_all = text_view_all.replace(/%s/gi, total);

				var url = "";
				

				url += '?q=' + g.term;

				if(category_id) {
					url += '&cat=' + encodeURIComponent(category_id);
				}

				return $(ul).append('<li><a href="<?php echo $this->getCatalogSearchLink(); ?>'+url+'" onclick="window.location=this.href">'+text_view_all+'</a></li>');
			};
			$(selector).find('input[name=\'<?php echo $catalogSearchHelper->getQueryParamName() ?>\']').data( "autocomplete" )._renderItem = function( ul, item ) {
				var html = item.html;

				var li_element = $("<li></li>").data("item.autocomplete",item).append(html).appendTo(ul);
				
				$(li_element).click(function(el){
					$(selector+' input[name=\'search\']').val('');
					if(item.link){
						window.location = item.link.replace(/&amp;/gi,'&');
					}
				});
				
				return li_element;
			};
	})
})(jQuery);
</script>